# Generated by Django 6.0.1 on 2026-08-24 19:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Padrão 1h (07h às 17h)', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tempo_fabricacao', models.DecimalField(decimal_places=3, help_text='Tempo em minutos para fabricar 1 par completo', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor')], default='supervisor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.setor')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('padrao', 'Padrão'), ('numerada', 'Numerada')], max_length=20)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to=settings.AUTH_USER_MODEL)),
                ('grade_horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='core.gradehorario', verbose_name='Grade de Horários')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='core.operador')),
            ],
        ),
        migrations.CreateModel(
            name='IntervaloHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem cronológica (1, 2, 3...)')),
                ('rotulo', models.CharField(help_text='Ex: 07:00-08:00 ou 07:00-07:30', max_length=50)),
                ('e_extra', models.BooleanField(default=False, help_text='Marque se este for o slot de Hora Extra')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='core.gradehorario')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('grade', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ItemFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.PositiveBigIntegerField(help_text='Numeração do calçado')),
                ('quantidade_planejada', models.PositiveIntegerField(blank=True, help_text="Só usado em fichas Numeradas: o 'X' de pares a produzir", null=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.ficha')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelo')),
            ],
            options={
                'unique_together': {('ficha', 'modelo', 'numeracao')},
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tempo_fabricacao', models.DecimalField(decimal_places=3, help_text='Tempo em minutos para fabricar 1 unidade dessa peça', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='core.modelo')),
            ],
            options={
                'unique_together': {('modelo', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='operador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='core.setor'),
        ),
        migrations.CreateModel(
            name='ItemFichaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_planejada', models.PositiveIntegerField(blank=True, help_text="Só usado em fichas Numeradas: o 'X' de peças a produzir", null=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('item_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_habilitadas', to='core.itemficha')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitacoes', to='core.peca')),
            ],
            options={
                'unique_together': {('item_ficha', 'peca')},
            },
        ),
        migrations.CreateModel(
            name='RegistroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzida', models.PositiveIntegerField(default=0)),
                ('quantidade_perda', models.PositiveIntegerField(blank=True, default=0, help_text='Quantidade de peças/pares perdidos')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('item_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.itemficha')),
                ('peca', models.ForeignKey(blank=True, help_text='Deixe em branco se o registro for do par completo (modelo)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.peca')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.intervalohorario', verbose_name='Período/Horário')),
            ],
            options={
                'unique_together': {('item_ficha', 'peca', 'periodo')},
            },
        ),
    ]
