# Generated by Django 6.0.1 on 2026-08-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='grade_horario',
        ),
        migrations.AlterUniqueTogether(
            name='registroproducao',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='GradeHorario',
        ),
        migrations.RemoveField(
            model_name='registroproducao',
            name='periodo',
        ),
        migrations.DeleteModel(
            name='IntervaloHorario',
        ),
    ]
