# Generated by Django 6.0.1 on 2026-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_intervalohorario_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='total_planejado',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade total planejada para fichas numeradas.', null=True, verbose_name='Total Planejado Geral'),
        ),
    ]
